### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by omarsawalhah** [lschilde/Sharing_APEX_SERT_23_1#1]
DB Version 19.9
APEX Version 23.1
Pluggable db
I am getting this error
PL/SQL procedure successfully completed.

PL/SQL procedure successfully completed.

=============================================================================
== Application File apex-sert_admin.sql Complete
=============================================================================

=============================================================================
== Web Service File Start
=============================================================================

=============================================================================
== Application File apex-sert_admin.sql Complete
=============================================================================

=============================================================================
== R E C O M P I L E   C O R E	 S C H E M A
=============================================================================
=============================================================================
== A P P L I C A T I O N   I N S T A L L A T I O N   R E S U L T S
=============================================================================

    APP_ID WORKSPACE		APPLICATION_NAME
---------- -------------------- ------------------------------
       195 SERT 		APEX-SERT
       196 SERT 		APEX-SERT Administration
=============================================================================
== P O S T   I N S T A L L A T I O N   S T E P S
=============================================================================

In order to be able to launch APEX-SERT, paste the following into the System Message
region in the INTERNAL workspace:

<a href="javascript:var launchSERT=window.open('sert/launch/' + $v('pInstance'));"><span class="a-Icon icon-run-page"></span>&nbsp;Launch APEX-SERT</a>

To access the APEX-SERT Admin application, enter the following URL while
substituting HOST, PORT and DAD with those from your APEX environment:

http(s)://HOST:PORT/DAD/f?p=SERT_ADMIN

Please see the APEX-SERT Installation Guide for detailed post-installation steps.

connect as SV_SERT_LAUNCHER for SERT Launcher Web Service part 2
ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect
descriptor

**Comment by lschilde** [comment]
Thanks for raising this.... the issue here is simple there is a connection string in each install.sql file which you need to change before you actually run the installation. This is general rule with this installation set and I tried commenting in the code explaining what each thing is doing so it is easy to adjust to your use-case. 


Once you get connection string correctly everything will work fine.

**Comment by lschilde** [comment]
You can create a REST service manually now but I would simply rerun the installation once you figure the connection string.

**Comment by omarsawalhah** [comment]
> You can create a REST service manually now but I would simply rerun the installation once you figure the connection string.

What exactly is the script needed to create the REST, and where to put exactly the TNS?

**Comment by omarsawalhah** [comment]
I think it is apex-sert_launcher_part2.sql script asuming I am connected to SV_SERT_LAUNCHER. user,

**Comment by lschilde** [comment]
Yes that is the correct script

On Tuesday, July 11, 2023, omarsawalhah ***@***.***> wrote:
> I think it is apex-sert_launcher_part2.sql script asuming I am connected
to SV_SERT_LAUNCHER. user,
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci3.googleusercontent.com/proxy/sxdq7QhaTDfSAJgDKcdGBXxySGRPvSCseHW7nZuOmwoANTYGqY9rQUPQHgD9ayaZ9nFJ-oDFQgtoBrljdkHO_oYWOAs0yXyUu0tJ5IUL0VcmAC5VFerGfwhrayvp6H7XhjlHBlwFPnzJx8SzIZukZpsp-4nEWLJ0xuH4Vt_j8SWVjcf9cf1KvVMdCG2UWhOH7SsrUGAPJ779J75y6-mv1F8WXOXLEuCk6724Nxa4U1EqT7SpZw=s0-d-e1-ft#https://github.com/notifications/beacon/ABND76SKPJNBTLESIKXGI7TXPUEJHA5CNFSM6AAAAAA2FROMVSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTBFWAWU.gif>Message
ID: ***@***.***>
